services:
  api:
    command: uv run uvicorn main:app --host 0.0.0.0 --port 4000 --reload
    volumes:
      - ./backend/api:/app
    environment:
      DEBUG: "true"

  web:
    command: npm run dev
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
    volumes:
      - ./frontend/web:/app
      - /app/node_modules
      - /app/.next
