FROM node:22-alpine

WORKDIR /app

COPY package.json ./
COPY tsconfig.base.json ./
COPY apps/api/package.json ./apps/api/package.json
COPY packages/contracts/package.json ./packages/contracts/package.json
COPY apps/api ./apps/api
COPY packages/contracts ./packages/contracts

RUN npm install

EXPOSE 4000

CMD ["npm", "run", "start:api"]
